version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
      
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Helllooooo World..!" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/output.txt
            - build/*
   print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat output.txt
      
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
